### ISSUE TITLE
Arzela Ascoli

### ISSUE THREAD

**Issue by Tovermodus** [hd-notes/notes#16]
In dem Ana script befindet sich In Satz 3.29 ein recht großer Fehler, denn die Funktionenfolge muss hier nicht gleichmäßig stetig sondern gleichgradig stetig sein, in dem Kriterium muss statt |x - a| <= delta_epsilon auch stehen |x - y | < delta_epsilon.
Vielen Dank, dass du den Aufwand in den Vorlesiúngen auf dich genommen hast, Top Arbeit!

**Comment by rroohhh** [comment]
Danke für den Hinweis!
